logo: 'images/aroga-logo.png'
slides:
  - desktop: 'images/slider/kids-w1302.jpg'
    mobile: 'images/slider/kids-w301.jpg'
    alt: 'Kids playing on farm'
  - desktop: 'images/slider/basket-w1305.jpg'
    mobile: 'images/slider/basket_w299.jpg'
    alt: 'A basket on farm land'
  - desktop: 'images/slider/farm-w1305.jpg'
    mobile: 'images/slider/farm-299.jpg'
    alt: 'A farm'

journey:
  banner:
    desktop: 'images/journey/flower_field-w-602.jpg'
    mobile: 'images/journey/flower_field_w290.jpg'
  heading: Our Journey
  subtitle: What started as a simple dream took form when an army veteran and his wife took a liking to their mission and gave them land to bring their vision into reality.
  button:
    text: Know More
    icon: icon-arrow-right
  details:
    - icon: icon-sun
      title: No-Chemical Produce
      subtitle: We are using natural ingredients only when creating our produce and no chemicals.
    - icon: icon-thumbs-up
      title: Pestiside Residue
      subtitle: Our produces are tested for pesticide residue on labs which state we have no pestisides.
    - icon: icon-user-check
      title: Nutritous & Non-Toxic
      subtitle: Our produce are more nutritious in values and non-toxic during processes.

reviews:
  subtitle: Customer Reviews
  heading: What our Customers are saying
  list:
    - name: Prajakta Gokhale
      image: 'images/reviews/prajakta.jpg'
      review: >
        Very fresh and good quality veggies. They freshly harvest and within 6 hours home delivered which is an added advantage. 
        
        Theirs greens are the best
        Good luck to Team Aroga Living.
    - name: Krishna Chaitanya
      image: 'images/reviews/krishna.jpg'
      review: >
        Ever since we moved to Aroga, I found the green leafy veggies to be tender & crisp and the assurance of organic farm to home, impeccable delivery and hassle free ordering and payments and above all the right work culture and responsive management of everything right from plantation to delivering it home, we’ve been enjoying the produce without questions regards quality in our minds...
    - name: Renu Danewa
      review: >
        Earlier ( before Aroga ) it was always an apprehensive buying because of quality issues, water used, etc etc.This winter has been the best for.me and my family. 
        *heartfelt gratitude to Prateek and Team Aroga* for providing us super fresh, clean, lots of variety of greens.
    - name: Vishali S
      image: 'images/reviews/vishali.jpg'
      review: >
        Love the fresh and crunchy green veggies delivered. Kudos to the team and Prateek for their efforts to ensure on time deliveries and honesty.

subscribe:
  subtitle: Our Newsletter
  heading: Sign Up to Our Newsletter
  action: Sign Up

footer:
  social:
    - icon: icon-facebook
      link: https://facebook.com
    - icon: icon-linked-in
      link: https://linkedin.com
    - icon: icon-Instagram
      link: https://instagram.com
  menus:
    - title: Categories
      list:
        - title: Features
          link: /featured
        - title: Best Selling
          link: /best-selling
        - title: Quality Scale
          link: /quality-scale
    - title: Legal
      list:
        - title: Terms of Service
          link: /terms
        - title: Privacy Policy
          link: /privacy-policy
        - title: Laboratory Test
          link: /laboratory-test
    - title: Company
      list:
        - title: About
          link: /about
        - title: Team
          link: /team
        - title: Contact
          link: /contact